// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKEYh9_slEi34ENhvn1bRTiWzOrnz68gA',
    appId: '1:67043335009:android:72d0e6b1ed763e79e68320',
    messagingSenderId: '67043335009',
    projectId: 'proyectofinaldam-107d0',
    storageBucket: 'proyectofinaldam-107d0.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGh_k1KhSCs5p35u5RuSB97t53VDSe7o',
    appId: '1:67043335009:web:eaa5d73671b328f6e68320',
    messagingSenderId: '67043335009',
    projectId: 'proyectofinaldam-107d0',
    authDomain: 'proyectofinaldam-107d0.firebaseapp.com',
    storageBucket: 'proyectofinaldam-107d0.appspot.com',
    measurementId: 'G-EQ76GGSTZQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOzxmg5DYryuvwqQXThpZ6FbuFXjZklxQ',
    appId: '1:67043335009:ios:e4fb55a9f0abbc2de68320',
    messagingSenderId: '67043335009',
    projectId: 'proyectofinaldam-107d0',
    storageBucket: 'proyectofinaldam-107d0.appspot.com',
    iosBundleId: 'com.gps.finalproject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOzxmg5DYryuvwqQXThpZ6FbuFXjZklxQ',
    appId: '1:67043335009:ios:e4fb55a9f0abbc2de68320',
    messagingSenderId: '67043335009',
    projectId: 'proyectofinaldam-107d0',
    storageBucket: 'proyectofinaldam-107d0.appspot.com',
    iosBundleId: 'com.gps.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgGh_k1KhSCs5p35u5RuSB97t53VDSe7o',
    appId: '1:67043335009:web:997ef3822ebc012ae68320',
    messagingSenderId: '67043335009',
    projectId: 'proyectofinaldam-107d0',
    authDomain: 'proyectofinaldam-107d0.firebaseapp.com',
    storageBucket: 'proyectofinaldam-107d0.appspot.com',
    measurementId: 'G-YJK2DCJKVG',
  );

}